---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.2.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-v1
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: '2.2'
    checks:
      - gradle:publish
      - gradle:properties:version
